// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSetting.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MyJiraWork.Core.Utils.UserSetting {

  /// <summary>Holder for reflection information generated from UserSetting.proto</summary>
  public static partial class UserSettingReflection {

    #region Descriptor
    /// <summary>File descriptor for UserSetting.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserSettingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFVc2VyU2V0dGluZy5wcm90bxIIdHV0b3JpYWwilwEKC1VzZXJTZXR0aW5n",
            "EhkKEUppcmFTZXJ2ZXJBZGRyZXNzGAEgASgJEhQKDEppcmFVc2VyTmFtZRgC",
            "IAEoCRIUCgxKaXJhUGFzc3dvcmQYAyABKAkSEwoLUHJveHlTZXJ2ZXIYBCAB",
            "KAkSFQoNUHJveHlVc2VyTmFtZRgFIAEoCRIVCg1Qcm94eVBhc3N3b3JkGAYg",
            "ASgJQiSqAiFNeUppcmFXb3JrLkNvcmUuVXRpbHMuVXNlclNldHRpbmdiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MyJiraWork.Core.Utils.UserSetting.UserSetting), global::MyJiraWork.Core.Utils.UserSetting.UserSetting.Parser, new[]{ "JiraServerAddress", "JiraUserName", "JiraPassword", "ProxyServer", "ProxyUserName", "ProxyPassword" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  [START messages]
  /// </summary>
  public sealed partial class UserSetting : pb::IMessage<UserSetting> {
    private static readonly pb::MessageParser<UserSetting> _parser = new pb::MessageParser<UserSetting>(() => new UserSetting());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MyJiraWork.Core.Utils.UserSetting.UserSettingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSetting(UserSetting other) : this() {
      jiraServerAddress_ = other.jiraServerAddress_;
      jiraUserName_ = other.jiraUserName_;
      jiraPassword_ = other.jiraPassword_;
      proxyServer_ = other.proxyServer_;
      proxyUserName_ = other.proxyUserName_;
      proxyPassword_ = other.proxyPassword_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSetting Clone() {
      return new UserSetting(this);
    }

    /// <summary>Field number for the "JiraServerAddress" field.</summary>
    public const int JiraServerAddressFieldNumber = 1;
    private string jiraServerAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JiraServerAddress {
      get { return jiraServerAddress_; }
      set {
        jiraServerAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "JiraUserName" field.</summary>
    public const int JiraUserNameFieldNumber = 2;
    private string jiraUserName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JiraUserName {
      get { return jiraUserName_; }
      set {
        jiraUserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "JiraPassword" field.</summary>
    public const int JiraPasswordFieldNumber = 3;
    private string jiraPassword_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JiraPassword {
      get { return jiraPassword_; }
      set {
        jiraPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProxyServer" field.</summary>
    public const int ProxyServerFieldNumber = 4;
    private string proxyServer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProxyServer {
      get { return proxyServer_; }
      set {
        proxyServer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProxyUserName" field.</summary>
    public const int ProxyUserNameFieldNumber = 5;
    private string proxyUserName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProxyUserName {
      get { return proxyUserName_; }
      set {
        proxyUserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ProxyPassword" field.</summary>
    public const int ProxyPasswordFieldNumber = 6;
    private string proxyPassword_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProxyPassword {
      get { return proxyPassword_; }
      set {
        proxyPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (JiraServerAddress != other.JiraServerAddress) return false;
      if (JiraUserName != other.JiraUserName) return false;
      if (JiraPassword != other.JiraPassword) return false;
      if (ProxyServer != other.ProxyServer) return false;
      if (ProxyUserName != other.ProxyUserName) return false;
      if (ProxyPassword != other.ProxyPassword) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (JiraServerAddress.Length != 0) hash ^= JiraServerAddress.GetHashCode();
      if (JiraUserName.Length != 0) hash ^= JiraUserName.GetHashCode();
      if (JiraPassword.Length != 0) hash ^= JiraPassword.GetHashCode();
      if (ProxyServer.Length != 0) hash ^= ProxyServer.GetHashCode();
      if (ProxyUserName.Length != 0) hash ^= ProxyUserName.GetHashCode();
      if (ProxyPassword.Length != 0) hash ^= ProxyPassword.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (JiraServerAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(JiraServerAddress);
      }
      if (JiraUserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(JiraUserName);
      }
      if (JiraPassword.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(JiraPassword);
      }
      if (ProxyServer.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProxyServer);
      }
      if (ProxyUserName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProxyUserName);
      }
      if (ProxyPassword.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ProxyPassword);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (JiraServerAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JiraServerAddress);
      }
      if (JiraUserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JiraUserName);
      }
      if (JiraPassword.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JiraPassword);
      }
      if (ProxyServer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProxyServer);
      }
      if (ProxyUserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProxyUserName);
      }
      if (ProxyPassword.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProxyPassword);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserSetting other) {
      if (other == null) {
        return;
      }
      if (other.JiraServerAddress.Length != 0) {
        JiraServerAddress = other.JiraServerAddress;
      }
      if (other.JiraUserName.Length != 0) {
        JiraUserName = other.JiraUserName;
      }
      if (other.JiraPassword.Length != 0) {
        JiraPassword = other.JiraPassword;
      }
      if (other.ProxyServer.Length != 0) {
        ProxyServer = other.ProxyServer;
      }
      if (other.ProxyUserName.Length != 0) {
        ProxyUserName = other.ProxyUserName;
      }
      if (other.ProxyPassword.Length != 0) {
        ProxyPassword = other.ProxyPassword;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            JiraServerAddress = input.ReadString();
            break;
          }
          case 18: {
            JiraUserName = input.ReadString();
            break;
          }
          case 26: {
            JiraPassword = input.ReadString();
            break;
          }
          case 34: {
            ProxyServer = input.ReadString();
            break;
          }
          case 42: {
            ProxyUserName = input.ReadString();
            break;
          }
          case 50: {
            ProxyPassword = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
